IMAGE_INSTALL_append += "\
    qtcharts \
    qtconnectivity \
    qtdeclarative \
    qtimageformats \
    qtlocation \
    qtmqtt \
    qtmultimedia \
    qtquickcontrols \
    qtquickcontrols2 \
    qtscript \
    qtsensors \
    qtserialbus \
    qtserialport \
    qtsvg \
    qtsystems \
    qttools \
    qttranslations \
    qtwebchannel \
    qtwebsockets \
    qtxmlpatterns \
    packagegroup-qt5-toolchain-target \
    qt3d \
    qtgraphicaleffects \
    qtwayland \
"
