#!/bin/bash
#Copyright (c) 2008 Wind River Systems, Inc.
#description : Death-notify unit test
# 
#developer : Yongli He  <yongli.he@windriver.com>
#
# changelog 
# * 
# - 

TOPDIR=${CUTDIR-/opt/cut/}
. $TOPDIR/function.sh


clean()
{
     rm -rf death-notify.log
    echo "Death-notify unit test complete"

}

zcat /proc/config.gz | grep CONFIG_SIGEXIT=y || cuterr "Configure CONFIG_SIGEXIT=y first"

echo  -n "Testing death notify.....:"
$TOPDIR/bin/death-notify 2>&1 > death-notify.log

cat death-notify.log

msg=$( cat death-notify.log | grep "child1 notify child2 of child1's exit.")

if [ "X$msg" = "X" ]; then
	cutfail 
fi

cutpass

