wallpaper_image = Image("wrl.png");
screen_width = Window.GetWidth();
screen_height = Window.GetHeight();
resized_wallpaper_image = wallpaper_image.Scale(screen_width,screen_height);
wallpaper_sprite = Sprite(resized_wallpaper_image);
wallpaper_sprite.SetZ(-100);

#Sets the background white. Alternatively you can do a gradient by setting different colors
Window.SetBackgroundTopColor (1.0, 1.0, 1.0);
Window.SetBackgroundBottomColor (1.0, 1.0, 1.0);
